os:
  - linux
  - osx

language: go

go: 1.9

before_install:
  - export PATH=~/.eclectica/versions/node/current/bin:$PATH
  - export PATH=~/.eclectica/versions/rust/current/bin:$PATH
  - export PATH=~/.eclectica/versions/ruby/current/bin:$PATH
  - export PATH=~/.eclectica/versions/go/current/bin:$PATH
  - export PATH=~/.eclectica/versions/python/current/bin:$PATH
  - export PATH=~/.eclectica/versions/elm/current/bin:$PATH
  - export PATH=~/.eclectica/bin:$PATH
  - export PATH=~/.eclectica/shared/bin:$PATH

  - echo $PATH
  - echo $HOME

install:
  - make install

script:
  - make test

matrix:
  include:

    # trusty
    - env: "TEST_LANGUAGE=main"
      os: linux
      dist: trusty
      script: "travis_wait make int-ci"

    - env: "TEST_LANGUAGE=node"
      os: linux
      dist: trusty
      script: "travis_wait make int-ci"

    - env: "TEST_LANGUAGE=rust"
      os: linux
      dist: trusty
      script: "travis_wait 40 make int-ci"

    - env: "TEST_LANGUAGE=ruby"
      os: linux
      dist: trusty
      before_install:
        - export PATH=~/.eclectica/versions/node/current/bin:$PATH
        - export PATH=~/.eclectica/versions/rust/current/bin:$PATH
        - export PATH=~/.eclectica/versions/ruby/current/bin:$PATH
        - export PATH=~/.eclectica/versions/go/current/bin:$PATH
        - export PATH=~/.eclectica/versions/python/current/bin:$PATH
        - export PATH=~/.eclectica/versions/elm/current/bin:$PATH
        - export PATH=~/.eclectica/bin:$PATH
        - export PATH=~/.eclectica/shared/bin:$PATH

        - echo $PATH
        - echo $HOME

        # C++14
        - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        - sudo apt-get update -qq
      install:
        - "make install"

        # C++14
        - sudo apt-get install -qq g++-6
        - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
      script: "travis_wait 400 make int-ci"

    - env: "TEST_LANGUAGE=go"
      os: linux
      dist: trusty
      script: "travis_wait make int-ci"

    - env: "TEST_LANGUAGE=python2.7"
      os: linux
      dist: trusty
      script: "travis_wait 400 make int-ci"

    - env: "TEST_LANGUAGE=python2-old"
      os: linux
      dist: trusty
      script: "travis_wait 400 make int-ci"

    - env: "TEST_LANGUAGE=python3"
      os: linux
      dist: trusty
      script: "travis_wait 400 make int-ci"

    - env: "TEST_LANGUAGE=elm"
      os: linux
      dist: trusty
      script: "travis_wait make int-ci"

    # precise
    - env: "TEST_LANGUAGE=main"
      os: linux
      dist: precise
      script: "travis_wait make int-ci"

    - env: "TEST_LANGUAGE=node"
      os: linux
      dist: precise
      script: "travis_wait make int-ci"

    - env: "TEST_LANGUAGE=rust"
      os: linux
      dist: precise
      script: "travis_wait 40 make int-ci"

    - env: "TEST_LANGUAGE=ruby"
      os: linux
      dist: precise
      before_install:
        - export PATH=~/.eclectica/versions/node/current/bin:$PATH
        - export PATH=~/.eclectica/versions/rust/current/bin:$PATH
        - export PATH=~/.eclectica/versions/ruby/current/bin:$PATH
        - export PATH=~/.eclectica/versions/go/current/bin:$PATH
        - export PATH=~/.eclectica/versions/python/current/bin:$PATH
        - export PATH=~/.eclectica/versions/elm/current/bin:$PATH
        - export PATH=~/.eclectica/bin:$PATH
        - export PATH=~/.eclectica/shared/bin:$PATH

        - echo $PATH
        - echo $HOME

        # C++14
        - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        - sudo apt-get update -qq
      install:
        - "make install"

        # C++14
        - sudo apt-get install -qq g++-6
        - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
      script: "travis_wait 400 make int-ci"

    - env: "TEST_LANGUAGE=go"
      os: linux
      dist: precise
      script: "travis_wait make int-ci"

    - env: "TEST_LANGUAGE=python2.7"
      os: linux
      dist: precise
      script: "travis_wait 400 make int-ci"

    - env: "TEST_LANGUAGE=python2-old"
      os: linux
      dist: precise
      script: "travis_wait 400 make int-ci"

    - env: "TEST_LANGUAGE=python3"
      os: linux
      dist: precise
      script: "travis_wait 400 make int-ci"

    - env: "TEST_LANGUAGE=elm"
      os: linux
      dist: precise
      script: "travis_wait make int-ci"

    # osx
    - env: "TEST_LANGUAGE=main"
      os: osx
      script: "travis_wait make int-ci"

    - env: "TEST_LANGUAGE=node"
      os: osx
      script: "travis_wait make int-ci"

    - env: "TEST_LANGUAGE=rust"
      os: osx
      script: "travis_wait make int-ci"

    - env: "TEST_LANGUAGE=ruby"
      os: osx
      script: "travis_wait make int-ci"

    - env: "TEST_LANGUAGE=go"
      os: osx
      script: "travis_wait make int-ci"

    - env: "TEST_LANGUAGE=python2.7"
      os: osx
      script: "travis_wait 400 make int-ci"

    - env: "TEST_LANGUAGE=python2-old"
      os: osx
      script: "travis_wait 400 make int-ci"

    - env: "TEST_LANGUAGE=python3"
      os: osx
      script: "travis_wait 400 make int-ci"

    - env: "TEST_LANGUAGE=elm"
      os: osx
      script: "travis_wait make int-ci"
