name: CI
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        go-version: [1.19.x]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PATH
        run: export PATH="$(ec path):$PATH"
      - name: Run Tests
        run: make test
      - name: Run Integration Tests
        run: make integration-ci
